### ISSUE TITLE
Support Pingback

### ISSUE THREAD

**Issue by muety** [willnorris/webmention#10]
As Webmentions and Pingbacks are closely related, are there plans to extend this tool to be able to send Pingbacks as well?

**Comment by willnorris** [comment]
I hadn't really planned to.  Sites wanting to support both is certainly reasonable, and indeed it looks like a number of webmention implementations documented on https://indieweb.org/Webmention also support pingback.  

However, I wonder if a separate pingback library would be a better separation?  There would be a little bit of common code for parsing HTTP and HTML links, but the whole library is still pretty small.

**Comment by muety** [comment]
Thanks for your feedback!
